name: Preview deployment
on:
  push:
    branches:
      - prev
env:
  DOCKER_IMAGE_NAME: azure-directus-image-${{ github.base_ref || github.ref_name }}
  IMAGE_REGISTRY_URL: ghcr.io
  AZURE_WEBAPP_NAME: azure-directus-${{ github.base_ref || github.ref_name }}
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    name: Build docker image
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create .env config file from GitHub secrets
        run: |
          echo "${{ secrets.CONFIG_PREV_ENV }}" > .env
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - name: 'Build and push image'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.IMAGE_REGISTRY_URL }}
          username: ${{ github.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
            docker build . -t ${{ env.IMAGE_REGISTRY_URL }}/${{ env.REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
            docker push ${{ env.IMAGE_REGISTRY_URL }}/${{ env.REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}

  deploy-to-azure:
    runs-on: ubuntu-latest
    needs: build-docker-image
    name: Deploy app container
    steps:
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Lowercase the github.actor
        run: echo "actor=${GITHUB_ACTOR,,}" >>${GITHUB_ENV}
      - name: Lowercase the repo name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
      - uses: azure/docker-login@v1
        with:
          login-server: ${{env.IMAGE_REGISTRY_URL}}
          username: ${{ env.actor }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Deploy web app container
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{env.AZURE_WEBAPP_NAME}}
          images: ${{ env.IMAGE_REGISTRY_URL }}/${{ env.REPO }}/${{ env.DOCKER_IMAGE_NAME }}:${{ github.sha }}
      - name: Azure logout
        run: |
          az logout
