name: Destroy Azure environment

on:
  workflow_dispatch:
    inputs:
      resource_group:
        description: "Name of resource group to destroy"
        required: true
        default: 'research'
      sure:
        description: 'Are you sure to destroy all resources?'
        required: true
        type: boolean

env:
  AZURE_RESOURCE_GROUP: ${{ github.event.inputs.resource_group }}

jobs:
  destroy-azure-resources:
    runs-on: ubuntu-latest

    steps:

      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Destroy Azure environment
        if: success()
        run: |
          az group delete --name ${{env.AZURE_RESOURCE_GROUP}} --subscription ${{secrets.AZURE_SUBSCRIPTION_ID}} --yes
